# application.yml: 스프링부트 설정 파일
# 요즘은 .properties보다 .yml을 많이 사용하는 추세
# xml, json, yml, properties 등 다양한 설정 파일이 존재하지만, 스프링부트에서는 yml이 가독성이 좋고, 계층 구조를 표현하기 편리하여 많이 사용됨

spring:
  jpa:
    show-sql: true # 전송 쿼리 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # 쿼리를 보기좋게 포맷팅

    defer-datasource-initialization: true # 테이블 생성 후에 data.sql 실행

  datasource:
    url: jdbc:h2:mem:testdb # h2 데이터베이스 url(jdbc:h2:mem:xxx 형식)

  h2:
    console:
        enabled: true # h2 콘솔 활성화(http://localhost:8080/h2-console)