# application.yml: 스프링부트 설정 파일
# 요즘은 .properties보다 .yml을 많이 사용하는 추세
# xml, json, yml, properties 등 다양한 설정 파일이 존재하지만, 스프링부트에서는 yml이 가독성이 좋고, 계층 구조를 표현하기 편리하여 많이 사용됨

spring:
  config:
    import: optional:file:.secret/application-local.yml # 로컬 환경에서만 필요한 설정을 별도의 파일로 분리해서 관리할 수 있음. .secret/application-local.yml 파일은 git에 올리지 않음

  jpa:
    show-sql: true # 전송 쿼리 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # 쿼리를 보기좋게 포맷팅
    defer-datasource-initialization: true # 테이블 생성 후에 data.sql 실행
#  datasource:
#    url: jdbc:h2:mem:testdb # h2 데이터베이스 url(jdbc:h2:mem:xxx 형식)
#    user: sa # h2 데이터베이스 사용자명
  h2:
    console:
        enabled: true # h2 콘솔 활성화(http://localhost:8080/h2-console)
  security:
    oauth2:
      client:
        registration:
          google: # 깃허브 안 올라가도록 조심
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              # - openid # 구글에서 발급하는 불변 사용자 식별자 sub
              - email # 구글 계정 이메일 email
              - profile # 구글 계정 프로필 정보(전체 이름 name, 이름 given_name, 성 family_name, 프로필 사진 picture 등)
