DROP DATABASE IF EXISTS blog;
DROP DATABASE IF EXISTS BLOG;

CREATE DATABASE BLOG
    CHARACTER SET utf8mb4 -- 이모티콘 지원
    COLLATE utf8mb4_unicode_ci; -- 대소문자 구분 없는 정렬

USE BLOG;

CREATE TABLE USERS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, -- BIGINT: MYSQL에서 일반 사용 ,UNSIGNED: 음수 불가, AUTO_INCREMENT: 자동 증가
    EMAIL VARCHAR(320) NOT NULL, -- VARCHAR: MYSQL에서 일반 사용, 320: 이메일 최대 길이
    PASSWORD VARCHAR(255) NULL, -- 255: 비밀번호 최대 길이
    NICKNAME VARCHAR(100) NOT NULL, -- 100: 닉네임 최대 길이
    ROLE TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1: ADMIN, 2: USER, 3: OTHER',
    AUTH_PROVIDER VARCHAR(30) NOT NULL DEFAULT 'GOOGLE',
    PROVIDER_USER_ID VARCHAR(255) NULL, -- 추후 sub 사용
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 디비 레벨에서 현재 시간 저장
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 디비 레벨에서 현재 시간 저장
        ON UPDATE CURRENT_TIMESTAMP, -- updated_at 컬럼이 업데이트 될 때마다 현재 시간으로 갱신
    PRIMARY KEY (ID),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_USERS_PROVIDER_USER UNIQUE (AUTH_PROVIDER, PROVIDER_USER_ID),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN (1, 2, 3))
) ENGINE = InnoDB; -- MySQL의 기본 스토리지 엔진, 외래 키 제약 조건과 트랜잭션을 디비가 지원

CREATE TABLE ARTICLE (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    AUTHOR_ID BIGINT UNSIGNED NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    SUMMARY VARCHAR(500) NULL, -- articleList.html에서 보여줄 요약
    CONTENT LONGTEXT NOT NULL,
    VIEW_COUNT BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PINNED TINYINT(1) NOT NULL DEFAULT 0,
    LANGUAGE VARCHAR(100) NOT NULL DEFAULT 'korean',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 조회수 등이 변경될 때는 변경되면 안되기 때문에 ON UPDATE CURRENT TIMESTAMP 제거
    PRIMARY KEY (ID),
    CONSTRAINT CK_ARTICLE_PINNED CHECK (PINNED IN (0, 1)),
    CONSTRAINT FK_ARTICLE_AUTHOR
        FOREIGN KEY (AUTHOR_ID) REFERENCES USERS (ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT FK_ARTICLE_PINNED_BY
        FOREIGN KEY (PINNED_BY) REFERENCES USERS (ID)
        ON UPDATE RESTRICT
        ON DELETE SET NULL,
    INDEX IX_ARTICLE_AUTHOR_ID (AUTHOR_ID),
    INDEX IX_ARTICLE_LIST (PINNED, CREATED_AT)
) ENGINE = InnoDB;

CREATE TABLE ARTICLE_LIKE (
    ARTICLE_ID BIGINT UNSIGNED NOT NULL,
    USER_ID BIGINT UNSIGNED NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ARTICLE_ID, USER_ID),
    CONSTRAINT FK_ARTICLE_LIKE_ARTICLE
        FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    CONSTRAINT FK_ARTICLE_LIKE_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    INDEX IX_ARTICLE_LIKE_USER_ID (USER_ID)
) ENGINE = InnoDB;

-- Store image files outside the database and insert IMAGE_URL into Summernote HTML.
CREATE TABLE ARTICLE_IMAGE (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ARTICLE_ID BIGINT UNSIGNED NOT NULL,
    STORAGE_KEY VARCHAR(512) NOT NULL,
    IMAGE_URL VARCHAR(2048) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR(255) NULL,
    CONTENT_TYPE VARCHAR(100) NOT NULL,
    FILE_SIZE BIGINT UNSIGNED NOT NULL,
    ALT_TEXT VARCHAR(255) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT UQ_ARTICLE_IMAGE_STORAGE_KEY UNIQUE (STORAGE_KEY),
    CONSTRAINT FK_ARTICLE_IMAGE_ARTICLE
        FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID)
        ON UPDATE RESTRICT
        ON DELETE CASCADE,
    INDEX IX_ARTICLE_IMAGE_ARTICLE_ID (ARTICLE_ID)
) ENGINE = InnoDB;

CREATE TABLE REFRESH_TOKEN (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT UNSIGNED NOT NULL,
    REFRESH_TOKEN VARCHAR(512) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, -- 디비 레벨에서 현재 시간 저장
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 디비 레벨에서 현재 시간 저장
        ON UPDATE CURRENT_TIMESTAMP, -- updated_at 컬럼이 업데이트 될 때마다 현재 시간으로 갱신
    PRIMARY KEY (ID),
    CONSTRAINT UQ_REFRESH_TOKEN_USER_ID UNIQUE (USER_ID),
    CONSTRAINT UQ_REFRESH_TOKEN_VALUE UNIQUE (REFRESH_TOKEN),
    CONSTRAINT FK_REFRESH_TOKEN_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
        ON UPDATE RESTRICT -- 리프레시 토큰이 참조 중이면 USERS.ID 변경을 제한
        ON DELETE CASCADE -- 사용자가 삭제되면 해당 사용자의 리프레시 토큰도 삭제
) ENGINE = InnoDB;
