# nginx 설정 파일
# 빌드된 .jar 파일과 형제 디렉토리로 .platform/nginx/conf.d/xxx.conf 파일을 .zip 파일로 압축하여 배포하면, AWS Elastic Beanstalk에서 자동으로 nginx 설정을 적용

client_max_body_size 50M; # aws 앞에는 nginx가 있어서 파일 업로드 제한 설정이 있는데 이를 50M로 향상 (기본값은 1M)
